### ISSUE TITLE
请问下图标该怎么自定义

### ISSUE THREAD

**Issue by Nico-M** [muggledy/typora-dyzj-theme#11]
嗨,主题非常的棒. 想问下,font-icon一共有哪些,可以自定义吗? font-icon 是来自什么库吗? 谢谢

**Comment by muggledy** [comment]
你好，Typora提供了[Font Awesome4.x](https://fontawesome.dashgame.com/)版本的图标，风车图标我是用的[阿里矢量图标库](https://www.iconfont.cn/)，当前项目里，只提供了如下几个图标字体（字体文件下载在本地，见`source/dy/iconfont.min.css`）：
![image](https://user-images.githubusercontent.com/26343222/148548014-1a353a92-826e-4df1-82ff-4b4373435b46.png)
之所以使用上述阿里图标，是因为默认的Font Awesome库中没有风车图标
如果你需要使用其他图标，以Font Awesome图标为例（其他类似），示例如下：
```css
h1:before {
    font-family: FontAwesome;
    content: "\f001"; //音乐图标
}
```
![image](https://user-images.githubusercontent.com/26343222/148549552-bfb57bcb-41ed-4029-845f-198c21726961.png)
`content`值可以在`Typora安装目录\resources\app\style\font-awesome-4.1.0\css\font-awesome.css`中搜索，而常见的图标使用方式是通过font class引用，如`<i class="fa fa-music"></i>`，但这并不能用于Typora

**Comment by muggledy** [comment]
或者从[EmojiXD](https://emojixd.com/group/animals-nature)复制图标：
```css
h1:before {
    content: "🍒";
}
```
![image](https://user-images.githubusercontent.com/26343222/148550818-adc932ac-0a22-4e91-87e6-7605227bc13f.png)
